branches:
  only:
    - f/travis-test
language: python
python:
  - "2.7"
env:
  global:
    - CPAN_OPTS="-I"
before_install: 
  - perl --version
  - mkdir ~/.cpan/CPAN
  - cpan -J > ~/.cpan/CPAN/Config.pm
  - cpan YAML::XS
script: 
  - ./test/testMoa.sh
  - ./buildMoa.sh
